### ISSUE TITLE
command line instructions: rdforms or cpsv-ap_creator

### ISSUE THREAD

**Issue by barthanssens** [catalogue-of-services-isa/cpsv-ap_rdf_editor#1]
The command line instructions include:

```
Before you can use the editor you need to make sure all the dependencies are loaded. Simply run:
$ cd path_to_rdforms
```
Is this really about the RDForms library, or should it read cd path_to_cpsv-ap_creator ?

Same goes for `After having installed the dependencies, build RDForms`

**Comment by carmenvandeloo** [comment]
The CPSV-AP Creator uses the RDForms Javascript library as explained in the introduction text of the readme file. I have updated the "Command-line installation instructions" section to make this more clear.
