### ISSUE TITLE
COFOG URI:s

### ISSUE THREAD

**Issue by peterk** [catalogue-of-services-isa/cpsv-ap_rdf_editor#3]
The tool creates URI:s for COFOG categories in a way that does not seem consistent with the [UN COFOG SKOS file](https://web.archive.org/web/20161102181141/http://unstats.un.org/unsd/cr/downloads/COFOG_rdf.zip).

E.g. selecting 07 Health will render the following URI for dcterms:type:

`https://unstats.un.org/unsd/cr/registry/regcs.asp?Cl=4&amp;Lg=1&amp;Co=07`

The UN COFOG SKOS RDF file uses this URI for 07 Health:

`http://unstats.un.org/unsd/cr/references/cofog/version1/07`

**Comment by EmidioStani** [comment]
This project is going to be archived
